- name: Install prerequisites
  apt:
    name: [apt-transport-https, ca-certificates, curl, gnupg-agent, software-properties-common]
    state: present
    update_cache: true

- name: Add Dockerofficial GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repo
  apt:
    name: docker-ce
    state: latest
    update_cache: true

- name: Ensure docker service is running
  service:
    name: docker
    state: running
    enabled: true
