apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-deploy
  namespace: echo-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: echo
    template:
      metadata:
        labels:
          app: echo
      spec:
        containers:
          - name: echo
            image: tropt1/echo-app:latest
            env:
              - name: AUTHOR
                value: "tropt1 (Maxim Bolotov)"
              ports:
                - containerPort: 8000
                  readinessProbe:
                    httpGet:
                      path: /
                      port: 8000
                    initialDelaySeconds: 5
                    periodSeconds: 10
                  livenessProbe:
                    httpGet:
                      path: /
                      port: 8000
                    initialDelaySeconds: 15
                    periodSeconds: 20
